# Generated by Django 3.2.8 on 2022-03-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
