# Generated by Django 3.2.8 on 2022-03-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='person',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
